### ISSUE TITLE
NativeWebcamJNI(2427): VIDIOC_DQBUF error 9, Bad file number

### ISSUE THREAD

**Issue by mishraakhilesh** [openxc/android-webcam#13]
i am getting an error while starting the application.
NativeWebcamJNI(2427): VIDIOC_DQBUF error 9, Bad file number

this error keeps repeating. There is no other message of error that I see.

**Comment by mishraakhilesh** [comment]
Now I am getting following error. Not sure what changed.
NativeWebcamJNI(2825): VIDIOC_DQBUF error 22, Invalid argument

**Comment by mishraakhilesh** [comment]
After some digging and exploration i could get this working with following changes

```
//*fd = open(dev_name, O_RDWR | O_NONBLOCK, 0);
*fd = open(dev_name, O_RDWR);
```

**Comment by peplin** [comment]
Thanks, added to the README

**Comment by i-khan** [comment]
Yes It worked, thanks. Please if you can write some detail about this error and how you solved it.
