### ISSUE TITLE
Bridge unity3d

### ISSUE THREAD

**Issue by nebnes** [openxc/android-webcam#8]
I am not a developer and i am looking for solution to connect an external camera  to unity3d. 
I would like to know if this library it's a good starter to make a bridge between android and unity 3d ?

**Comment by peplin** [comment]
Hey there, no experience with Unity 3D myself so can't say if this is a good place to start or not. If Unity has its own APIs for interacting with UVC cameras, that may be easier. Anyone else?

**Comment by nebnes** [comment]
I have not find anything with UVC cameras and Unity 3d.
But it's possible to make a android native plugins for unity but I don't know how include the webcam library ...
I follow this tutorial: http://www.codestalkers.com/blog/android-plugins

Or maybe use the library directly with unity: http://docs.unity3d.com/Manual/PluginsForAndroid.html ?

**Comment by peplin** [comment]
The Plugins For Android section seems to indicate you can use this library directly. There's probably a bit more to it, but I would try that first.

**Comment by nebnes** [comment]
Ok thanks, I have no experience with android. Do you have any advices to start ?

**Comment by peplin** [comment]
I think the advice on that Unity page is sound, "To build a plugin for Android, you should first obtain the Android NDK and familiarize yourself with the steps involved in building a shared library." Let me know if you get stuck farther along in the process, I can try and help.
