### ISSUE TITLE
Insufficient permissions on /dev/video0 

### ISSUE THREAD

**Issue by nebnes** [openxc/android-webcam#9]
Hi ! 

When I run the example I have this "Insufficient permissions on /dev/video0  -- does the app have the CAMERA permission?" in the console. 

I have check the permission in the manifest and I have also check the permission in adb: 
"crw-rw---- system   camera    81,   1 2014-09-11 21:15 video0"

thanks in advance

**Comment by etiology** [comment]
Your permissions are not correct. The user needs to be media and the group needs to be camera (please check this is the manual). So 'chown media /dev/video0' to fix it

**Comment by etiology** [comment]
From README:
"If the file is at least 0660, owned by the media user with the group camera, you're good to go.

Add the CAMERA permissions to your app's manifest:"

**Comment by nebnes** [comment]
Ok Thanks ! 
I have other question, I tried this app: https://play.google.com/store/apps/details?id=infinitegra.trial.usbcamera 

Why this app haven't need permission  ?

**Comment by peplin** [comment]
Added an FAQ to the README, thanks.
